- name: get_url | download k3s
  get_url:
    url: "https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s"
    dest: /opt/k3s
    owner: root
    group: root
    mode: 0750
    checksum: "sha256:https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt"
  notify:
    - restart k3s-server

- name: template | configure systemd unit for k3s-server
  template:
    src: k3s-server.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0640
  notify:
    - restart k3s-server
  ignore_errors: "{{ ansible_check_mode }}"
  diff: "{{ 'server' in group_names }}"
